# signs:
#     - artifacts: checksum

project_name: udptl-parser
builds:
    - id: udptl-parser
      binary: "udptl-parser-{{.Tag}}"
      env:
        - CGO_ENABLED=1
      goos:
        - linux
      goarch:
        - amd64
      ignore:
        - goos: freebsd
          goarch: arm
        - goos: freebsd
          goarch: arm64
        - goos: windows
          goarch: arm
        - goos: windows
          goarch: arm64
      dir: cmd/udptl-parser
      main: ./main.go
      ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}} -extldflags '-static'"

archives:
  - id: udptl-parser
    name_template: >-
       udptl-parser_
       {{- .Tag}}_
       {{- if eq .Os "darwin"}}macos
       {{- else}}{{.Os}}{{end}}_
       {{- if eq .Arch "amd64"}}x86_64
       {{- else if eq .Arch "386"}}i386
       {{- else}}{{.Arch}}{{end}}
    format: tar.gz
    builds:
      - udptl-parser

nfpms:
  - id: udptl-parser
    package_name: udptl-parser
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Improcom
    homepage: https://github.com/olegromanchuk/udptl-parser
    maintainer: Oleg Ro <oleg@romanchuk.us>
    description: An utility that parses pcap file and display which udptl streams exist.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
    release: 1