name: build

on:
  push:
    branches:
      - qa
      - hotfix
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install libpcap
        run: sudo apt-get install libpcap-dev

      - name: check out code
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod tidy

      - name: go test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=profile.cov ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github