name: build

on:
  push:
    branches:
      - qa
      - hotfix
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install static libraries
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev
          sudo apt-get install libexpat1-dev
          sudo apt-get install autoconf-archive
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config flex bison xz-utils
          wget https://dbus.freedesktop.org/releases/dbus/dbus-1.15.8.tar.xz
          tar -xvf dbus-1.15.8.tar.xz
          cd dbus-1.15.8
          ./autogen.sh
          ./configure --disable-shared --enable-static --prefix=/usr/local
          make
          sudo make install
          wget https://www.tcpdump.org/release/libpcap-1.10.1.tar.gz
          tar -xzf libpcap-1.10.1.tar.gz
          cd libpcap-1.10.1
          export LDFLAGS="-L/usr/local/lib -static"
          export CPPFLAGS="-I/usr/local/include"
          export LIBS="-ldbus-1"
          ./configure --disable-shared --prefix=/usr/local
          make
          sudo make install

      - name: check out code
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod tidy

      - name: go test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=profile.cov ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github