name: release

on:
  push:
    tags:
      - v*


jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Install libpcap
        run: echo "deb http://security.ubuntu.com/ubuntu bionic-security main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt-get install libpcap-dev

      - name: check out code
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod tidy

      - name: go test
        run: |
          go test -v -timeout=100s ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          CGO_ENABLED=1
          CGO_CFLAGS="-I/usr/local/include"  # Adjust if your include path differs
          CGO_LDFLAGS="-L/usr/local/lib -lpcap -ldbus-1 -static"  # Link statically
