name: release

on:
  push:
    tags:
      - v*


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install libpcap
        run: |
          sudo apt-get update
          sudo apt-get install libdbus-1-dev
          sudo apt-get install libexpat1-dev
          sudo apt-get install autoconf-archive
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config flex bison xz-utils
          wget https://dbus.freedesktop.org/releases/dbus/dbus-1.15.8.tar.xz
          tar -xvf dbus-1.15.8.tar.xz
          cd dbus-1.15.8
          ./autogen.sh
          ./configure --disable-shared --enable-static --prefix=/usr/local
          make
          sudo make install
          wget https://www.tcpdump.org/release/libpcap-1.10.1.tar.gz
          tar -xzf libpcap-1.10.1.tar.gz
          cd libpcap-1.10.1
          export LDFLAGS="-L/usr/local/lib -static"
          export CPPFLAGS="-I/usr/local/include"
          export LIBS="-ldbus-1"
         ./configure --disable-shared --prefix=/usr/local
          make
          sudo make install

      - name: check out code
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod tidy

      - name: go test
        run: |
          go test -v -timeout=100s ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          CGO_ENABLED=1
          CGO_CFLAGS="-I/usr/local/include"  # Adjust if your include path differs
          CGO_LDFLAGS="-L/usr/local/lib -lpcap -ldbus-1 -static"  # Link statically
