name: release

on:
  push:
    tags:
      - v*


jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:

      - name: Install libpcap
        run: sudo apt-get install libpcap-dev

      - name: check out code
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Get dependencies
        run: go mod tidy

      - name: go test
        run: |
          go test -v -timeout=100s ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}